name: build-push-docker

on:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - .github/workflows/build-push-docker.yml
      - .dockerignore
      - Dockerfile
      - src/**
      - nginx.default.conf

env:
  IMAGE_PREFIX: kalioz/canary-deployment-ui

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get version
        run: echo "VERSION=$(cat src/version)" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}-ying
          tags: |
            ${{ env.IMAGE_PREFIX }}:ying
            ${{ env.IMAGE_PREFIX }}:latest
            ${{ env.IMAGE_PREFIX }}:${{ env.VERSION }}-ying
            ${{ env.IMAGE_PREFIX }}:${{ env.VERSION }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}-yang
          tags: |
            ${{ env.IMAGE_PREFIX }}:yang
            ${{ env.IMAGE_PREFIX }}:${{ env.VERSION }}-yang
            